# This is the halloween themed Starship prompt.
format = """
[îƒ€ ](bg:#0c4347 fg:#75b3b7)\
$os\
$username\
[îƒ€](bg:#75b3b7 fg:#0c4347)\
$directory\
[îƒ€](fg:#75b3b7 bg:#0c4347)\
$git_branch\
$git_status\
[îƒ€](fg:#0c4347 bg:#75b3b7)\
$time\
[îƒ€](fg:#75b3b7 bg:#0c4347)\
$cmd_duration\
[îƒ€  ](fg:#0c4347)\
"""
# A new line at the beginning
add_newline = true

# Show the username.
[username]
show_always = true
style_user = "bg:#0c4347 fg:#75b3b7"
style_root = "bg:#00b6ba"
format = '[$user ]($style)'
disabled = false

# Display OS
[os]
style = "bg:#0c4347"
disabled = false # Disabled by default

# Insert a symbol of your OS to the prompt. This is all symbols added.
# You can add text also within this double quotes.
# That is, instead of the Arch Linux icon, you can get
# " ó°£‡  I use Arch BTW "
[os.symbols]
AlmaLinux = "ïŒ "
Alpine = "ïŒ€ "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ïŒŸ "
CachyOS = "î± "
CentOS = "î¼½ "
Debian = "î½ "
DragonFly = "î»¸ "
EndeavourOS = "ïŒ¢ "
Fedora = "îŸ™ "
FreeBSD = "ïŠ "
Garuda = "ïŒ· "
Gentoo = "îŸ¦ "
Kali = "ïŒ§ "
Linux = "ï…¼ "
Macos = "îœ‘ "
Manjaro = "ïŒ’ "
Mint = "ó°£­ "
NetBSD = "ğŸš© "
NixOS = "ó±„… "
Nobara = "ï€ "
OpenBSD = "ïŒ¨ "
openSUSE = "î¡— "
OracleLinux = "ó°«¼ "
Pop = "ïŒª "
Raspbian = "îœ¢ "
Redhat = "î½ "
RedHatEnterprise = "î½ "
RockyLinux = "î¢‘ "
Solus = "ïŒ­ "
SUSE = "î½­ "
Ubuntu = "î½² "
Unknown = "î¯ƒ "
Void = "ïŒ® "
Windows = "î˜ª "

# Show the directory details. Some directory, like the main ones are
# substituted with icons in the next sections.
[directory]
style = "bg:#75b3b7 fg:#0c4347"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Popular directories like Downloads, Documents, etc. are substituted
# with icons. This reduces space usage. You can add your own icons, given
# Nerd fonts are installed on your system.
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

# Display the git branch details, like master bracnch.
[git_branch]
symbol = "ï˜"
style = "bg:#57FFFF fg:#000000"
format = '[ $symbol $branch ]($style)'

# Display git status. This and the above show any visible output
# only if the current directory is initialized as a git directory.
# All other directories will not show this part.
# If you have background colors set for these, in the absence of git
# directory, they still appear in the prompt, empty.
[git_status]
style = "bg:#57FFFF fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

# Display time.
[time]
disabled = false
time_format = "%b %d, %I:%M %P" # Hour:Minute Format
style = "bg:#75b3b7 fg:#0c4347"
format = "[ $time ]($style)"

# Display command duration.
# Minimum time to display is set to 2000ms (2s).
# So, the prompt will display command duration only for commands that
# are running for more than 2 seconds. This is to avoid printing
# execution time for regular commands like ls and clear.
[cmd_duration]
disabled = false
min_time = 2000
style = 'bg:#0c4347 fg:#75b3b7'
format = '[ Took $duration!]($style)'
