format = """
[îƒ€ ](bg:#fec249)\
$os\
$username\
[îƒ€](bg:#ff5757 fg:#fec249)\
$directory\
[îƒ€](fg:#ff5757 bg:#57FFFF)\
$git_branch\
$git_status\
[îƒ€](fg:#57FFFF bg:#ff66c4)\
$time\
[îƒ€](fg:#ff66c4 bg:#5ce1e6)\
$cmd_duration\
[îƒ€  ](fg:#5ce1e6)\
"""
# A new line at the beginning
add_newline = true

[username]
show_always = true
style_user = "bg:#fec249 fg:#000000"
style_root = "bg:#00b6ba"
format = '[$user ]($style)'
disabled = false

# Display OS
[os]
style = "bg:#fec249"
disabled = false # Disabled by default

# Insert a symbol of your OS to the prompt. This is all symbols added.
[os.symbols]
AlmaLinux = "ïŒ "
Alpine = "ïŒ€ "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ïŒŸ "
CachyOS = "î± "
CentOS = "î¼½ "
Debian = "î½ "
DragonFly = "î»¸ "
EndeavourOS = "ïŒ¢ "
Fedora = "îŸ™ "
FreeBSD = "ïŠ "
Garuda = "ïŒ· "
Gentoo = "îŸ¦ "
Kali = "ïŒ§ "
Linux = "ï…¼ "
Macos = "îœ‘ "
Manjaro = "ïŒ’ "
Mint = "ó°£­ "
NetBSD = "ğŸš© "
NixOS = "ó±„… "
Nobara = "ï€ "
OpenBSD = "ïŒ¨ "
openSUSE = "î¡— "
OracleLinux = "ó°«¼ "
Pop = "ïŒª "
Raspbian = "îœ¢ "
Redhat = "î½ "
RedHatEnterprise = "î½ "
RockyLinux = "î¢‘ "
Solus = "ïŒ­ "
SUSE = "î½­ "
Ubuntu = "î½² "
Unknown = "î¯ƒ "
Void = "ïŒ® "
Windows = "î˜ª "

[directory]
style = "bg:#ff5757 fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#57FFFF fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#57FFFF fg:#000000"
format = '[$all_status$ahead_behind ]($style)'


[time]
disabled = false
time_format = "%b %d, %I:%M %P" # Hour:Minute Format
style = "bg:#ff66c4 fg:#000000"
format = "[ $time ]($style)"

[cmd_duration]
disabled = false
min_time = 2000
style = 'bg:#5ce1e6 fg:#000000'
format = '[ Took $duration!]($style)'
